# -*- coding: utf-8 -*-
"""Feedback_AI_Model_BERT_Training_Sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hp16cEjD6hi2hhL3iRRg1eGy_jKsREbf
"""

!pip install transformers
!pip install datasets
!pip install torch
!pip install pandas
!pip install scikit-learn

import pandas as pd
import numpy as np
import torch

from transformers import BertTokenizer
from transformers import BertForSequenceClassification
from transformers import Trainer
from transformers import TrainingArguments

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from google.colab import files
uploaded = files.upload()

data = pd.read_csv("sentiment_dataset_bert.csv")
data.head()

label_map = {
"Negative":0,
"Positive":1,
"Neutral":2,
}

data["label"] = data["sentiment"].map(label_map)

train_texts, val_texts, train_labels, val_labels = train_test_split(
data["feedback"],
data["label"],
test_size=0.2
)

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

train_encodings = tokenizer(
list(train_texts),
truncation=True,
padding=True
)

val_encodings = tokenizer(
list(val_texts),
truncation=True,
padding=True
)

class FeedbackDataset(torch.utils.data.Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key,val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = FeedbackDataset(train_encodings, train_labels.tolist())
val_dataset = FeedbackDataset(val_encodings, val_labels.tolist())

model = BertForSequenceClassification.from_pretrained(
"bert-base-uncased",
num_labels=3
)

import transformers
print(transformers.__version__)

from transformers import TrainingArguments
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8
)

from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average='weighted')
    return {
        'accuracy': acc,
        'f1_score': f1
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

predictions = trainer.predict(val_dataset)
preds = np.argmax(predictions.predictions, axis=-1)
accuracy = accuracy_score(val_labels, preds)
f1 = f1_score(val_labels, preds, average='weighted')
print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")

model.save_pretrained("bert_sentiment_model")
tokenizer.save_pretrained("bert_sentiment_model")

import torch
label_map = {
    "Negative":0,
    "Positive":1,
    "Neutral":2
}

# Create a reverse mapping for predictions
reverse_label_map = {v: k for k, v in label_map.items()}

text = "system is very good"
inputs = tokenizer(text,return_tensors="pt",truncation=True, padding=True )
inputs = {key: value.to(model.device) for key, value in inputs.items()}
outputs = model(**inputs)
pred = outputs.logits.argmax().item()
print("Prediction Topic:",reverse_label_map[pred])



!zip -r bert_sentiment_model.zip bert_sentiment_model
from google.colab import files
files.download("bert_sentiment_model.zip")