# Generated by Django 6.0.3 on 2026-05-25 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activate_institution', 'Activate Institution'), ('deactivate_institution', 'Deactivate Institution'), ('delete_institution', 'Delete Institution'), ('activate_user', 'Activate User'), ('deactivate_user', 'Deactivate User'), ('change_password', 'Change Password'), ('update_profile', 'Update Profile')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'superadmin_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
