# Generated by Django 6.0.3 on 2026-06-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('activate_institution', 'Activate Institution'), ('deactivate_institution', 'Deactivate Institution'), ('delete_institution', 'Delete Institution'), ('approve_institution', 'Approve Institution'), ('reject_institution', 'Reject Institution'), ('activate_user', 'Activate User'), ('deactivate_user', 'Deactivate User'), ('change_password', 'Change Password'), ('update_profile', 'Update Profile')], max_length=50),
        ),
    ]
