# Generated by Django 6.0.3 on 2026-06-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('activate_institution', 'Activate Institution'), ('deactivate_institution', 'Deactivate Institution'), ('delete_institution', 'Delete Institution'), ('approve_institution', 'Approve Institution'), ('reject_institution', 'Reject Institution'), ('activate_user', 'Activate User'), ('deactivate_user', 'Deactivate User'), ('change_password', 'Change Password'), ('update_profile', 'Update Profile'), ('create_form', 'Create Form'), ('update_form', 'Update Form'), ('delete_form', 'Delete Form'), ('invite_user', 'Invite User'), ('update_user', 'Update User'), ('delete_user', 'Delete User')], max_length=50),
        ),
    ]
