# Generated by Django 6.0.3 on 2026-05-01 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('faculty_name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('coordinator', models.CharField(blank=True, default='', max_length=255)),
                ('lecturer', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.institution')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
