services:
  db:
    image: postgres:15
    container_name: thinkback_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:5432"

  redis:
    image: redis:7-alpine
    container_name: thinkback_redis
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: thinkback_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db

  backend:
    profiles:
      - app
    build: ./backend
    container_name: thinkback_backend
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  celery:
    profiles:
      - app
    build: ./backend
    container_name: thinkback_celery
    restart: always
    command: celery -A core worker --loglevel=info
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    profiles:
      - app
    build: ./frontend
    container_name: thinkback_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data: