# Generated by Django 6.0.3 on 2026-05-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('form_type', models.CharField(choices=[('Exam', 'Exam'), ('Lab', 'Lab'), ('Course', 'Course'), ('Custom', 'Custom')], default='Custom', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_forms', to='institutions.institution')),
            ],
            options={
                'db_table': 'feedback_forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('open_ended', 'Open Ended'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No'), ('rating', 'Rating')], default='open_ended', max_length=30)),
                ('options', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.feedbackform')),
            ],
            options={
                'db_table': 'feedback_questions',
                'ordering': ['order'],
            },
        ),
    ]
