# Generated by Django 6.0.3 on 2026-06-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedbackform_status'),
        ('institutions', '0002_add_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtoken',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_tokens', to='institutions.course'),
        ),
    ]
